### PR TITLE
add name lookup to startup script

### PR DESCRIPTION
**Pull request by grundrauschen**

### CODE REVIEW

**Comment by mgumz** [comment]
Why?

**Comment by grundrauschen** [comment]
When starting two different deployments in one kubernetes cluster, which are interconnected using vxlan, there is the problem, that the endpoints have to be configured during deployment, but the ip addresses of the services exposing this deployments are just available afterwards. To solve this problem, I added support of using FQDNs of the services for configurations, which will be converted during start to IP addresses and used for configuration. Usage in Helm charts will be made possible due to this change.

**Comment by mgumz** [comment]
That reads like a wonderful commit message ...

**Comment by thz** [comment]
What happens when the IPs change? We should watch for that, right?

**Pull request merged**
